services:
  - type: web
    name: heal-smart-backend
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
